### ISSUE TITLE
Theme Toggle not working 

### ISSUE THREAD

**Issue by jenlcmc** [UNLV-CS472-672/2024-S-GROUP6-RW#84]
**Describe the bug**
The theme toggle button is now not working anymore, there is no animation for it and when click it, it does nothing

**To Reproduce**
1. Go to any page
2. On the top right corner, click on toggle button

**Expected behavior**
It should switch between default light and dark theme

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
One of the new merges possibly could cause this issue. Especially if it is modify anything for the navBar

**Comment by esquek1** [comment]
The following merge from PR #70 or #73 probably caused this issue.

**Comment by jenlcmc** [comment]
I manage to fix it but will need to test more due to the fact that it could cause some error with Authentication component
